# 수치 처리

In [2]:
import numpy as np
import pandas as pd

data = [
    [120, 135, 150, 145],
    [100, 110, 140, 130],
    [90, 100, 95, 105]
]

print(data)

[[120, 135, 150, 145], [100, 110, 140, 130], [90, 100, 95, 105]]


In [10]:
sales_data = np.array(data)
print(np.sum(sales_data, axis=0))   # 세로 요소별
print(np.sum(sales_data, axis=1))   # 가로 요소별

[310 345 385 380]
[550 480 390]


In [14]:
profit_per_unit = np.array([20, 30, 25])

total_sales = np.dot(profit_per_unit, sales_data)

print(total_sales)


[7650 8500 9575 9425]


# 이미지 처리

In [ ]:
from PIL import img