# 탐색

In [301]:
import pandas as pd
import numpy as np

In [302]:
from sklearn.datasets import load_diabetes

load_diabetes = load_diabetes()

load_diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [303]:
df = pd.DataFrame(data=load_diabetes.data, columns=load_diabetes.feature_names)
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

# 머신러닝 프로세스

1. 데이터 수집
2. 데이터 전처리
3. 데이터 탐색

4. 모델 선정
5. 모델 학습
6. 모델 평가
7. 모델 개선
8. 모델 배포

In [304]:
# 1. 수집

from sklearn.datasets import load_iris

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [305]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=5)

In [306]:
# 모델 생성
from sklearn.tree import DecisionTreeClassifier as dtc

dt_clf = dtc()

# 모델 학습
fited = dt_clf.fit(x_train1, y_train)

NameError: name 'x_train1' is not defined

In [ ]:
# 모델 예측
pred = dt_clf.predict(X=x_test)
pred

array([1, 2, 2, 0, 2, 2, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2])

In [ ]:
# 모델 평가

from sklearn.metrics import accuracy_score

accuracy_score(pred, y_test)

0.9333333333333333

### 타이타닉

In [379]:
df = pd.read_csv("./data/titanic.csv")
df["Sex"] = df["Sex"].apply(lambda x: 0 if x=="male" else 1)
df2 = df.dropna()
df2

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
..                                                 ...  ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    1  47.0      1   
872                           Carlsson, Mr. Frans Olof    0  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    1  56.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
889                              Behr, Mr. Karl Howell    0  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [ ]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(df[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]], df["Survived"], test_size=0.2, random_state=42)

titanic_clf = dtc()

titanic_clf.fit(X=x_train1, y=y_train1)

pre = titanic_clf.predict(x_test1)



In [ ]:
x_train2, x_test2, y_train2, y_test2 = train_test_split(df2[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]], df2["Survived"], test_size=0.2, random_state=42)

titanic_clf2 = dtc()

titanic_clf2.fit(X=x_train2, y=y_train2)

pre2 = titanic_clf2.predict(x_test2)

In [ ]:
print(accuracy_score(y_test1, pre))
print(accuracy_score(y_test2, pre2))

0.7821229050279329
0.8108108108108109


## 의사결정나무 시각화

In [ ]:
import graphviz
from sklearn.tree import export_graphviz

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
export_graphviz(dt_clf, out_file="tree.dot", class_names=iris.target_names,)
with open("tree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

In [ ]:
export_graphviz(titanic_clf2, out_file="tree2.dot", class_names=x_train2.columns,)
with open("tree2.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

## 교차 검증

In [323]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5)
iris_clf = dtc(random_state=156)

iris.data, iris.target

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [328]:
for train_idx, test_idx in kfold.split(iris.data):
    x_train, x_test = iris.data[train_idx], iris.data[test_idx]
    y_train, y_test = iris.target[train_idx], iris.target[test_idx]

    iris_clf.fit(x_train, y_train)
    pred = iris_clf.predict(x_test)
    accuracy = accuracy_score(y_test, pred)
    print(f"Accuracy: {accuracy:.4f}")

Accuracy: 1.0000
Accuracy: 0.9667
Accuracy: 0.8667
Accuracy: 0.9333
Accuracy: 0.7333


In [334]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5)
for train_index, test_index in skf.split(iris.data, iris.target):
  y_train = iris.data[train_index]
  y_test =  iris.target[test_index]
  print(f'train 분포: {y_train}')
  print(f'test 분포: {y_test}')

train 분포: [[5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [

# GridSearchCV

In [407]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)

In [408]:
from sklearn.model_selection import GridSearchCV

dt_clf2 = dtc(random_state=121)

params = {'max_depth' : [1, 2, 3, 4], 'min_samples_split' : [2, 3, 4]}
grid_dtree = GridSearchCV(dt_clf2, param_grid=params, cv=5, refit=True)

grid_dtree.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=121),
             param_grid={'max_depth': [1, 2, 3, 4],
                         'min_samples_split': [2, 3, 4]})

In [409]:
pd.DataFrame(grid_dtree.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.000598      0.000488         0.000199        0.000399   
1        0.000401      0.000491         0.000399        0.000488   
2        0.000799      0.000400         0.000197        0.000395   
3        0.000397      0.000486         0.000197        0.000394   
4        0.000997      0.000005         0.000000        0.000000   
5        0.000400      0.000490         0.000201        0.000402   
6        0.000396      0.000485         0.000199        0.000398   
7        0.000598      0.000488         0.000199        0.000399   
8        0.000600      0.000490         0.000000        0.000000   
9        0.000397      0.000486         0.000199        0.000399   
10       0.000398      0.000488         0.000200        0.000400   
11       0.000397      0.000487         0.000199        0.000399   

   param_max_depth param_min_samples_split  \
0                1                       2   
1                1                       3   
2                1                       4   
3                2                       2   
4                2                       3   
5                2                       4   
6                3                       2   
7                3                       3   
8                3                       4   
9                4                       2   
10               4                       3   
11               4                       4   

                                      params  split0_test_score  \
0   {'max_depth': 1, 'min_samples_split': 2}           0.666667   
1   {'max_depth': 1, 'min_samples_split': 3}           0.666667   
2   {'max_depth': 1, 'min_samples_split': 4}           0.666667   
3   {'max_depth': 2, 'min_samples_split': 2}           0.875000   
4   {'max_depth': 2, 'min_samples_split': 3}           0.875000   
5   {'max_depth': 2, 'min_samples_split': 4}           0.875000   
6   {'max_depth': 3, 'min_samples_split': 2}           0.958333   
7   {'max_depth': 3, 'min_samples_split': 3}           0.958333   
8   {'max_depth': 3, 'min_samples_split': 4}           0.958333   
9   {'max_depth': 4, 'min_samples_split': 2}           0.875000   
10  {'max_depth': 4, 'min_samples_split': 3}           0.875000   
11  {'max_depth': 4, 'min_samples_split': 4}           0.958333   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.708333           0.708333           0.708333   
1            0.708333           0.708333           0.708333   
2            0.708333           0.708333           0.708333   
3            1.000000           1.000000           1.000000   
4            1.000000           1.000000           1.000000   
5            1.000000           1.000000           1.000000   
6            1.000000           1.000000           1.000000   
7            1.000000           1.000000           1.000000   
8            1.000000           1.000000           1.000000   
9            1.000000           1.000000           0.958333   
10           1.000000           1.000000           0.958333   
11           1.000000           1.000000           0.958333   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.708333         0.700000        0.016667               10  
1            0.708333         0.700000        0.016667               10  
2            0.708333         0.700000        0.016667               10  
3            0.916667         0.958333        0.052705                5  
4            0.916667         0.958333        0.052705                5  
5            0.916667         0.958333        0.052705                5  
6            0.916667         0.975000        0.033333                1  
7            0.916667         0.975000        0.033333                1  
8            0.916667         0.975000        0.033333                1  
9            0.916667         0.950000        0.048591                8  
10           0

In [410]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [411]:
pred = grid_dtree.predict(x_test)
accuracy_score(y_test, pred)

0.9666666666666667

## 타이타닉

In [432]:
x_train, x_test, y_train, y_test = train_test_split(df2[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]], df2["Survived"], test_size=0.189, random_state=42)

In [433]:
from sklearn.model_selection import GridSearchCV

dt_clf2 = dtc(random_state=121)

params = {'max_depth' : [1, 2, 3, 4], 'min_samples_split' : [2, 3, 4]}
grid_dtree = GridSearchCV(dt_clf2, param_grid=params, cv=5, refit=True)

grid_dtree.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=121),
             param_grid={'max_depth': [1, 2, 3, 4],
                         'min_samples_split': [2, 3, 4]})

In [434]:
pd.DataFrame(grid_dtree.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.002393  1.194495e-03         0.001593    4.898528e-04   
1        0.000997  4.422006e-07         0.000209    4.182816e-04   
2        0.000996  1.907349e-07         0.000997    2.780415e-07   
3        0.000997  1.168008e-07         0.000598    4.882662e-04   
4        0.000997  1.507891e-07         0.000598    4.883441e-04   
5        0.000997  1.784161e-07         0.000797    3.987313e-04   
6        0.000997  1.507891e-07         0.000598    4.883051e-04   
7        0.000997  2.780415e-07         0.000997    1.507891e-07   
8        0.000977  3.902952e-05         0.000635    5.196392e-04   
9        0.000959  3.605078e-05         0.000816    4.090108e-04   
10       0.001194  3.996006e-04         0.000000    0.000000e+00   
11       0.001000  4.023556e-06         0.000000    0.000000e+00   

   param_max_depth param_min_samples_split  \
0                1                       2   
1                1                       3   
2                1                       4   
3                2                       2   
4                2                       3   
5                2                       4   
6                3                       2   
7                3                       3   
8                3                       4   
9                4                       2   
10               4                       3   
11               4                       4   

                                      params  split0_test_score  \
0   {'max_depth': 1, 'min_samples_split': 2}           0.600000   
1   {'max_depth': 1, 'min_samples_split': 3}           0.600000   
2   {'max_depth': 1, 'min_samples_split': 4}           0.600000   
3   {'max_depth': 2, 'min_samples_split': 2}           0.633333   
4   {'max_depth': 2, 'min_samples_split': 3}           0.633333   
5   {'max_depth': 2, 'min_samples_split': 4}           0.633333   
6   {'max_depth': 3, 'min_samples_split': 2}           0.633333   
7   {'max_depth': 3, 'min_samples_split': 3}           0.633333   
8   {'max_depth': 3, 'min_samples_split': 4}           0.633333   
9   {'max_depth': 4, 'min_samples_split': 2}           0.633333   
10  {'max_depth': 4, 'min_samples_split': 3}           0.633333   
11  {'max_depth': 4, 'min_samples_split': 4}           0.633333   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.733333           0.800000           0.862069   
1            0.733333           0.800000           0.862069   
2            0.733333           0.800000           0.862069   
3            0.800000           0.766667           0.862069   
4            0.800000           0.766667           0.862069   
5            0.800000           0.766667           0.862069   
6            0.766667           0.733333           0.862069   
7            0.766667           0.733333           0.862069   
8            0.766667           0.733333           0.862069   
9            0.800000           0.700000           0.689655   
10           0.766667           0.666667           0.689655   
11           0.766667           0.666667           0.689655   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.689655         0.737011        0.090150                4  
1            0.689655         0.737011        0.090150                4  
2            0.689655         0.737011        0.090150                4  
3            0.689655         0.750345        0.080733                1  
4            0.689655         0.750345        0.080733                1  
5            0.689655         0.750345        0.080733                1  
6            0.551724         0.709425        0.107525                7  
7            0.551724         0.709425        0.107525                7  
8            0.551724         0.709425        0.107525                7  
9            0.551724         0.674943        0.081729               10  
10           0

In [435]:
grid_dtree.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [436]:
pred = grid_dtree.predict(x_test)
accuracy_score(y_test, pred)

0.8285714285714286

## 피처 스케일링

In [448]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [438]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [453]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled.mean()

np.float64(-1.4684549872375404e-15)

In [454]:
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(iris.data, 
                                                    iris.target, 
                                                    test_size=0.2, 
                                                    random_state=11 )

In [455]:
no_scaling_model = LogisticRegression(random_state=11)
no_scaling_model.fit(X_train, y_train)
pred_1 = no_scaling_model.predict(X_test)
acc_1 = accuracy_score(y_test, pred_1)
acc_1

0.9333333333333333

In [456]:
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
scaler1.fit(X_train)
X_train_scaled = scaler1.transform(X_train)
X_test_scaled = scaler1.transform(X_test)

In [457]:
scaling_model = LogisticRegression(random_state=11)
scaling_model.fit(X_train_scaled, y_train)
pred_2 = scaling_model.predict(X_test_scaled)
acc_2 = accuracy_score(y_test, pred_2)
acc_2, acc_1

(0.9, 0.9333333333333333)

### Titanic

In [562]:
df = pd.read_csv("./data/titanic.csv")
df["Sex"] = df["Sex"].apply(lambda x: 0 if x=="male" else 1)
df2 = df.dropna()
df2

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
..                                                 ...  ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    1  47.0      1   
872                           Carlsson, Mr. Frans Olof    0  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    1  56.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
889                              Behr, Mr. Karl Howell    0  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [582]:
x_train, x_test, y_train, y_test = train_test_split(df2[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]], df2["Survived"], test_size=0.2, random_state=42)

In [583]:
no_scaling_model = LogisticRegression(random_state=11)
no_scaling_model.fit(x_train, y_train)
pred_1 = no_scaling_model.predict(x_test)
acc_1 = accuracy_score(y_test, pred_1)
acc_1

0.7297297297297297

In [584]:
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
scaler1.fit(x_train, y_train)
X_train_scaled = scaler1.transform(x_train)
X_test_scaled = scaler1.transform(x_test)

In [585]:
scaling_model = LogisticRegression(random_state=42)
scaling_model.fit(X_train_scaled, y_train)
pred_2 = scaling_model.predict(X_test_scaled)
acc_2 = accuracy_score(y_test, pred_2)
acc_2, acc_1

(0.7297297297297297, 0.7297297297297297)